# Generated by Django 4.2 on 2023-04-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_state_upgrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='updates',
            name='championship',
            field=models.CharField(choices=[('S', 'Superbowl'), ('N', 'NBA Finals'), ('W', 'World Series')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='updates',
            name='date',
            field=models.DateField(verbose_name='Championship date'),
        ),
    ]
